# Generated by Django 2.1.3 on 2019-03-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='static/images/type_de_repro/logo_kfbleu.jpg', upload_to='static/images/type_de_repro/')),
            ],
        ),
    ]
